### ISSUE TITLE
RWMutex

### ISSUE THREAD

**Issue by nathanhack** [sasha-s/go-csync#1]
Is there any thought about making a RWMutex version of this?

**Comment by zhiqiangxu** [comment]
> Is there any thought about making a RWMutex version of this?

Here it is: https://github.com/zhiqiangxu/util/blob/master/mutex/crwmutex.go

**Comment by zhiqiangxu** [comment]
> Is there any thought about making a RWMutex version of this?

Here it is: https://github.com/zhiqiangxu/util/blob/master/mutex/crwmutex.go

**Comment by nathanhack** [comment]
That is awesome! Thanks!
