### ISSUE TITLE
Consider open sourcing this library?

### ISSUE THREAD

**Issue by matthiasr** [sasha-s/go-csync#4]
At the moment, this repository does not declare any open-source license. This means it is, by default, fully copyrighted. This is a problem because in practice, it is used in many open source projects, directly (e.g. [disgoorg/disgo](https://github.com/disgoorg/disgo/commit/6c253fabf95f4488eee925b4d81a09c3202b45a1)) or indirectly.

Would you consider open sourcing this library under an [appropriate license](https://github.com/disgoorg/disgo/commit/6c253fabf95f4488eee925b4d81a09c3202b45a1)? The Apache and MIT license are popular and most widely compatible with other licenses, but of course the choice is yours.

**Comment by matthiasr** [comment]
PS, since I just came across this guide: Making a repository public is [not enough](https://opensource.guide/legal/#are-public-github-projects-open-source) to make it open source.

**Comment by sasha-s** [comment]
Added apache license

**Comment by matthiasr** [comment]
Thank you!
